import os
import re
import pandas as pd
from dotenv import load_dotenv
from groq import Groq

load_dotenv()
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def load_data(filepath="data/processed_data.csv"):
    df = pd.read_csv(filepath, index_col=0, parse_dates=True)
    return df

def summarize_data(df):
    summary = {}
    for col in df.columns:
        summary[col] = {
            "Latest Price": round(df[col].iloc[-1], 2),
            "30-Day Average": round(df[col].tail(30).mean(), 2),
            "Standard Deviation (30D)": round(df[col].tail(30).std(), 2),
            "Total Return (%)": round(
                (df[col].iloc[-1] / df[col].iloc[0] - 1) * 100, 2
            ),
            "Max Price": round(df[col].max(), 2),
            "Min Price": round(df[col].min(), 2),
        }
    if len(df.columns) >= 2:
        corr_30d = df.tail(30).corr()
        corr_full = df.corr()
        cols = df.columns.tolist()
        for i in range(len(cols)):
            for j in range(i+1, len(cols)):
                summary[f"30D Correlation {cols[i]} vs {cols[j]}"] = round(corr_30d.loc[cols[i], cols[j]], 4)
                summary[f"Full Period Correlation {cols[i]} vs {cols[j]}"] = round(corr_full.loc[cols[i], cols[j]], 4)
    return summary

def get_visualization_paths():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    viz_dir = os.path.join(base_dir, "visualizations")
    charts = {
        "1. Price Trends Chart": os.path.join(viz_dir, "1_price_trends.png"),
        "2. Asset Correlation Matrix": os.path.join(viz_dir, "2_correlation.png"),
        "3. Return Distribution": os.path.join(viz_dir, "3_return_distribution.png"),
        "4. Bollinger Bands": os.path.join(viz_dir, "4_bollinger_bands.png"),
        "5. Volatility Comparison": os.path.join(viz_dir, "5_volatility_comparison.png"),
        "6. Drawdown Analysis": os.path.join(viz_dir, "6_drawdown_analysis.png"),
    }
    return charts

def run_agent(summary: dict, charts: dict) -> str:
    chart_list = "\n".join([f"- {name}: {path}" for name, path in charts.items()])
    prompt = f"""You are a senior financial analyst specializing in portfolio risk management and asset allocation.

Below is the statistical summary of S&P 500 and Gold over the analysis period:

{summary}

The following visualizations have been generated by the data team:
{chart_list}

Please write a comprehensive financial analysis report in English covering the following sections:

1. EXECUTIVE SUMMARY
   - Brief overview of key findings and market conditions
   - Overall recommendation in 2-3 sentences

2. PRICE TREND ANALYSIS (refer to Chart 1: Price Trends)
   - Detailed analysis of S&P 500 price movement with specific numbers
   - Detailed analysis of Gold price movement with specific numbers
   - Compare the trends between the two assets

3. VOLATILITY & RISK ASSESSMENT (refer to Chart 4: Bollinger Bands and Chart 5: Volatility Comparison)
   - Analyze standard deviation and what it means for each asset
   - Identify which asset carries higher risk and why
   - Assess current market conditions (overbought/oversold)

4. CORRELATION ANALYSIS (refer to Chart 2: Correlation Matrix)
   - Explain the 30-day short-term correlation coefficient with exact number
   - Explain the full-period long-term correlation coefficient with exact number
   - Discuss why these two numbers may differ
   - Interpret what the correlation means for portfolio diversification

5. RETURN DISTRIBUTION ANALYSIS (refer to Chart 3: Return Distribution)
   - Compare total returns of both assets with exact percentages
   - Analyze the distribution of daily returns
   - Identify any notable patterns or anomalies

6. DRAWDOWN ANALYSIS (refer to Chart 6: Drawdown Analysis)
   - Identify maximum drawdown periods for each asset
   - Assess downside risk for investors

7. PORTFOLIO ALLOCATION RECOMMENDATION
   - Provide specific percentage allocation (e.g., 60% S&P 500, 40% Gold)
   - Justify the recommendation with data from the analysis
   - Include risk management considerations

Use specific numbers from the data throughout the report. Be detailed and thorough. Reference the chart filenames where appropriate."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.4,
        max_tokens=3000,
    )
    return response.choices[0].message.content

def save_report(report: str, charts: dict, output_path="data/ai_report.txt"):
    RESET  = "\033[0m"
    BOLD   = "\033[1m"
    CYAN   = "\033[96m"
    YELLOW = "\033[93m"
    GREEN  = "\033[92m"
    BLUE   = "\033[94m"
    WHITE  = "\033[97m"
    DIM    = "\033[2m"
    RED    = "\033[91m"

    def highlight_numbers(text):
        text = re.sub(r'(\$[\d,\.]+)', YELLOW + r'\1' + WHITE, text)
        text = re.sub(r'([\d,\.]+%)', YELLOW + r'\1' + WHITE, text)
        text = re.sub(r'\b(-?[\d]+\.[\d]+)\b', GREEN + r'\1' + WHITE, text)
        return text

    print("\n" + CYAN + "═"*60 + RESET)
    print(BOLD + YELLOW + "  📊  AI FINANCIAL ANALYSIS REPORT" + RESET)
    print(CYAN + "═"*60 + RESET + "\n")

    for line in report.split("\n"):
        stripped = line.strip()
        if stripped.startswith(("1.", "2.", "3.", "4.", "5.", "6.", "7.")):
            print(BOLD + BLUE + line + RESET)
        elif stripped.startswith("**") and stripped.endswith("**"):
            clean = line.replace("**", "")
            print("\n" + BOLD + CYAN + clean + RESET)
        elif stripped.startswith("*") or stripped.startswith("-"):
            print(GREEN + "  •" + WHITE + highlight_numbers(line[1:]) + RESET)
        elif any(kw in stripped.upper() for kw in ["RECOMMENDATION", "SUMMARY", "CONCLUSION", "EXECUTIVE"]):
            print(BOLD + YELLOW + highlight_numbers(line) + RESET)
        elif stripped == "":
            print()
        else:
            print(WHITE + highlight_numbers(line) + RESET)

    print("\n" + CYAN + "─"*60 + RESET)
    print(BOLD + YELLOW + "  📁  VISUALIZATION FILES" + RESET)
    print(CYAN + "─"*60 + RESET)
    for name, path in charts.items():
        if os.path.exists(path):
            print(GREEN + "  ✓ " + RESET + BOLD + name + RESET)
            print(DIM + "    " + path + RESET)
        else:
            print(RED + "  ✗ " + RESET + name + DIM + " (not found)" + RESET)

    full_output = report + "\n\n" + "="*60 + "\nVISUALIZATION FILES:\n"
    for name, path in charts.items():
        full_output += f"- {name}: {path}\n"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(full_output)

    print("\n" + CYAN + "─"*60 + RESET)
    print(BOLD + GREEN + "  ✓ Report saved at: " + RESET + output_path)
    print(CYAN + "═"*60 + RESET + "\n")

if __name__ == "__main__":
    df = load_data()
    summary = summarize_data(df)
    charts = get_visualization_paths()
    report = run_agent(summary, charts)
    save_report(report, charts)